// COMMON
export const COMMON_REQUEST = 'COMMON_REQUEST';
export const COMMON_SUCCESS = 'COMMON_SUCCESS';
export const COMMON_FAILURE = 'COMMON_FAILURE';

// AUTH
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// BOARD
export const BOARD_LIST_REQUEST = 'BOARD_LIST_REQUEST';
export const BOARD_LIST_SUCCESS = 'BOARD_LIST_SUCCESS';
export const BOARD_LIST_FAILURE = 'BOARD_LIST_FAILURE';

export const BOARD_DETAIL_REQUEST = 'BOARD_DETAIL_REQUEST';
export const BOARD_DETAIL_SUCCESS = 'BOARD_DETAIL_SUCCESS';
export const BOARD_DETAIL_FAILURE = 'BOARD_DETAIL_FAILURE';

// JOIN - 본인인증
export const AUTH_CHECK_REQUEST = 'AUTH_CHECK_REQUEST';
export const AUTH_CHECK_SUCCESS = 'AUTH_CHECK_SUCCESS';
export const AUTH_CHECK_FAILURE = 'AUTH_CHECK_FAILURE';

// JOIN - 아이디 중복확인
export const ID_CHECK_REQUEST = 'ID_CHECK_REQUEST';
export const ID_CHECK_SUCCESS = 'ID_CHECK_SUCCESS';
export const ID_CHECK_FAILURE = 'ID_CHECK_FAILURE';

// JOIN - 최종 회원가입
export const JOIN_FINAL_REQUEST = 'JOIN_FINAL_REQUEST';
export const JOIN_FINAL_SUCCESS = 'JOIN_FINAL_SUCCESS';
export const JOIN_FINAL_FAILURE = 'JOIN_FINAL_FAILURE';

// TEST_GRID
export const PAGE_GRID_LIST_REQUEST = 'PAGE_GRID_LIST_REQUEST';
export const PAGE_GRID_LIST_SUCCESS = 'PAGE_GRID_LIST_SUCCESS';
export const PAGE_GRID_LIST_FAILURE = 'PAGE_GRID_LIST_FAILURE';


// TEST_GRID
export const BASIC_GRID_LIST_REQUEST = 'BASIC_GRID_LIST_REQUEST';
export const BASIC_GRID_LIST_SUCCESS = 'BASIC_GRID_LIST_SUCCESS';
export const BASIC_GRID_LIST_FAILURE = 'BASIC_GRID_LIST_FAILURE';